config:
  global:
    resolve_timeout: 5m
  route:
    receiver: "email"
    routes:
      - match:
          severity: "critical"
        receiver: "email"
  receivers:
    - name: "email"
      email_configs:
        - to: "your-email@example.com"
