# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: aws-node
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: node-app
#   template:
#     metadata:
#       labels:
#         app: node-app
#     spec:
#       containers:
#         - name: node-app
#           image: 471112983834.dkr.ecr.eu-west-2.amazonaws.com/my_repo
#           ports:
#             - containerPort: 3000


apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: 471112983834.dkr.ecr.eu-west-2.amazonaws.com/my_repo:latest
          ports:
            - containerPort: 3000